version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql

  drupal:
    build: .
    container_name: drupal
    ports:
      - 8080:80
    depends_on:
      - mysql
      # - memcached
    restart: unless-stopped
    volumes:
      - ./drupal9/config/custom_php.ini:/opt/drupal/custom_php.ini
      - ./drupal9/config/sync:/opt/drupal/config/sync
      - ./drupal9/web/modules:/opt/drupal/web/modules
      - ./drupal9/web/themes:/opt/drupal/web/themes
      - ./drupal9/web/profiles:/opt/drupal/web/profiles
      - ./drupal9/web/libraries:/opt/drupal/web/libraries
      - ./drupal9/web/sites:/opt/drupal/web/sites
      - ./drupal9/composer.json:/opt/drupal/composer.json
      - ./drupal9/composer.lock:/opt/drupal/composer.lock

  # memcached:
  #   container_name: memcached
  #   image: memcached:latest
  #   ports:
  #     - "11211:11211"

volumes:
  db-data: